-- =====================================================================
-- OBSOLETO — NO APLICAR
-- =====================================================================
-- Esta migracion NUNCA se aplico en produccion y ademas estaba ROTA/INSEGURA:
--   * Referenciaba columnas que no existen en profiles (business_name,
--     plan_type, metrics) y una funcion is_admin() inexistente -> habria
--     fallado o quedado a medias.
--   * Creaba la tabla `recomendaciones` con politicas USING(true) de SELECT y
--     UPDATE para el rol public: cualquiera con la anon key podia LEER todos los
--     emails (fuga de PII / RGPD) y SOBREESCRIBIR filas. Prohibido por CLAUDE.md.
--
-- Sustituida por:  migrations/referidos-arbol-multinivel.sql
--   (red de referidos multinivel real, contra el schema real, sin tabla de
--    emails publica, con guard de columnas sensibles y RPCs security definer).
--
-- Se conserva este archivo solo como marcador historico.
-- =====================================================================
